//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/PlayerInputer.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputer : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputer()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputer"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""77753093-9a34-4793-a16d-8d55fa1e48e2"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""22e337bc-e544-4098-99e7-f1f327580413"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""FrontPunch"",
                    ""type"": ""Button"",
                    ""id"": ""41af137f-38cf-4d23-a89a-3918d2f02c19"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BackPunch"",
                    ""type"": ""Button"",
                    ""id"": ""7f55ed0f-7095-4498-a63f-071a8ab080cc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FrontKick"",
                    ""type"": ""Button"",
                    ""id"": ""a8d2e39b-6834-4a79-b78f-f7da8e8ee89b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BackKick"",
                    ""type"": ""Button"",
                    ""id"": ""aaffffb4-f165-427d-809d-d5e97101ec9b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Amp"",
                    ""type"": ""Button"",
                    ""id"": ""c3a08b1c-7f6d-41d3-bc72-6961b411a2cf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""9e887ca2-225e-4000-8ea6-e3c126084252"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""67362680-a87f-46a4-b716-815a1609cebd"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""ab3c3541-2832-43c3-be30-485e97d0c847"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f260c33b-e947-4d28-9a20-77411ed8414a"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""8872dec5-6f82-44e9-ab99-8636f8a5389d"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e5ade9c2-1a35-4156-81cc-2fba84d5df16"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FrontPunch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0ee7e9a9-d6ad-4111-aa5d-6a871dbf722e"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BackPunch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c04f218e-e0d7-4614-a941-2b8638f9166a"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FrontKick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""214d4cd6-c3b6-42cb-813a-b4022fc9fdb5"",
                    ""path"": ""<Keyboard>/semicolon"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BackKick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""66d86647-7dac-4483-bf3a-694fd5bd94ab"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Amp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
        m_Player_FrontPunch = m_Player.FindAction("FrontPunch", throwIfNotFound: true);
        m_Player_BackPunch = m_Player.FindAction("BackPunch", throwIfNotFound: true);
        m_Player_FrontKick = m_Player.FindAction("FrontKick", throwIfNotFound: true);
        m_Player_BackKick = m_Player.FindAction("BackKick", throwIfNotFound: true);
        m_Player_Amp = m_Player.FindAction("Amp", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Move;
    private readonly InputAction m_Player_FrontPunch;
    private readonly InputAction m_Player_BackPunch;
    private readonly InputAction m_Player_FrontKick;
    private readonly InputAction m_Player_BackKick;
    private readonly InputAction m_Player_Amp;
    public struct PlayerActions
    {
        private @PlayerInputer m_Wrapper;
        public PlayerActions(@PlayerInputer wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Player_Move;
        public InputAction @FrontPunch => m_Wrapper.m_Player_FrontPunch;
        public InputAction @BackPunch => m_Wrapper.m_Player_BackPunch;
        public InputAction @FrontKick => m_Wrapper.m_Player_FrontKick;
        public InputAction @BackKick => m_Wrapper.m_Player_BackKick;
        public InputAction @Amp => m_Wrapper.m_Player_Amp;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @FrontPunch.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFrontPunch;
                @FrontPunch.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFrontPunch;
                @FrontPunch.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFrontPunch;
                @BackPunch.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBackPunch;
                @BackPunch.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBackPunch;
                @BackPunch.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBackPunch;
                @FrontKick.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFrontKick;
                @FrontKick.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFrontKick;
                @FrontKick.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFrontKick;
                @BackKick.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBackKick;
                @BackKick.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBackKick;
                @BackKick.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBackKick;
                @Amp.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAmp;
                @Amp.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAmp;
                @Amp.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAmp;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @FrontPunch.started += instance.OnFrontPunch;
                @FrontPunch.performed += instance.OnFrontPunch;
                @FrontPunch.canceled += instance.OnFrontPunch;
                @BackPunch.started += instance.OnBackPunch;
                @BackPunch.performed += instance.OnBackPunch;
                @BackPunch.canceled += instance.OnBackPunch;
                @FrontKick.started += instance.OnFrontKick;
                @FrontKick.performed += instance.OnFrontKick;
                @FrontKick.canceled += instance.OnFrontKick;
                @BackKick.started += instance.OnBackKick;
                @BackKick.performed += instance.OnBackKick;
                @BackKick.canceled += instance.OnBackKick;
                @Amp.started += instance.OnAmp;
                @Amp.performed += instance.OnAmp;
                @Amp.canceled += instance.OnAmp;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnFrontPunch(InputAction.CallbackContext context);
        void OnBackPunch(InputAction.CallbackContext context);
        void OnFrontKick(InputAction.CallbackContext context);
        void OnBackKick(InputAction.CallbackContext context);
        void OnAmp(InputAction.CallbackContext context);
    }
}
